# Generated by Django 3.2.3 on 2021-06-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20210602_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='name',
        ),
    ]
